name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        fdb_ver: ['7.1.61', '7.3.43']

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup fenv
        uses: ./
        with:
          fdb_ver: ${{ matrix.fdb_ver }}

      - name: Lint shell scripts
        run: $FENV_PATH/build.sh --exec shellcheck build.sh docker_tag.sh shim.sh

      - name: Lint Dockerfile
        run: $FENV_PATH/build.sh --exec hadolint Dockerfile

      - name: Verify FDB connection
        run: $FENV_PATH/build.sh --exec fdbcli --exec "status"
